Cy 237 linux related reports alerts
VatsalJagani/Splunk-Cyences-App-for-Splunk pull request #39
Opened 2021-07-13 14:46 UTC by babhalodia

2021-07-13 17:05 UTC, VatsalJagani requested changes

2021-07-13 17:59 UTC, VatsalJagani approved these changes

2021-07-13 18:26 UTC, babhalodia commented
> or we need to use

+ actually worked

2021-07-13 18:45 UTC, VatsalJagani commented on cyences_app_for_splunk/default/data/ui/views/cs_linux_reports.xml
> +          | eval data=if(count&gt;0, "Data Present", "Data Not Present") | table label, data</query>
Bro, forgot to mention, we need to add other data source here.

2021-07-13 18:46 UTC, VatsalJagani requested changes
forgot to mention, we need to add other data source here. (on the dashboard)

2021-07-14 10:38 UTC, VatsalJagani approved these changes

2021-07-14 10:42 UTC, merged